"""Telegram presentation seam for the canonical learning course catalog.

Callback/deep-link data is a request, never authority. Every render/start
resolves the course again through ``course_catalog`` and the canonical pool
registry before sampling questions. Challenge/Battle/random-all competitive
entry points stay outside this module.
"""
from __future__ import annotations

import logging
import random

from telegram import InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import ConversationHandler

from course_catalog import (
    SURFACE_TELEGRAM,
    CourseCatalogError,
    CourseEntry,
    UnknownCourseError,
    course_policy,
    legacy_level_config as catalog_legacy_level_config,
    list_courses,
    list_groups,
    resolve_course,
    resolve_course_pool,
)
from config import SPEED_MODE_TIMEOUT, TIMED_MODE_TIMEOUT
from telegram_conversation_states import ANSWERING, CHOOSING_LEVEL

logger = logging.getLogger(__name__)

_MODE_LABELS = {
    "relaxed": "🧘 Без ограничения времени",
    "timed": f"⏱ На время ({TIMED_MODE_TIMEOUT} сек)",
    "speed": f"⚡ Скоростной ({SPEED_MODE_TIMEOUT} сек)",
}
_MODE_LIMITS = {
    "relaxed": None,
    "timed": TIMED_MODE_TIMEOUT,
    "speed": SPEED_MODE_TIMEOUT,
}


def legacy_level_config() -> dict[str, dict]:
    """Compatibility view generated by the canonical catalog."""
    return catalog_legacy_level_config(surface=SURFACE_TELEGRAM)


def _learning_note(entry: CourseEntry) -> str:
    policy = course_policy(entry)
    if policy.scoring_mode == "learning":
        return "📚 Учебный режим · без рейтинговых баллов"
    return f"💎 {policy.points_per_question} балл(а) за верный ответ"


def _group_keyboard() -> InlineKeyboardMarkup:
    rows = []
    for group in list_groups(surface=SURFACE_TELEGRAM):
        courses = list_courses(surface=SURFACE_TELEGRAM, group=group.key)
        if not courses:
            continue
        if len(courses) == 1:
            callback = f"course:{courses[0].key}"
        else:
            callback = f"course_group:{group.key}"
        rows.append([
            InlineKeyboardButton(
                f"{group.icon} {group.title}",
                callback_data=callback,
            )
        ])
    rows.append([InlineKeyboardButton("⬅️ Назад", callback_data="back_to_main")])
    return InlineKeyboardMarkup(rows)


async def choose_level(update, context, is_callback: bool = False):
    """Catalog-backed production learning menu."""
    del context
    text = (
        "🎯 *ВЫБЕРИ КАТЕГОРИЮ*\n\n"
        "Доступные учебные модули загружаются из серверного каталога."
    )
    keyboard = _group_keyboard()
    if is_callback and update.callback_query:
        query = update.callback_query
        await query.edit_message_text(text, reply_markup=keyboard, parse_mode="Markdown")
    else:
        await update.message.reply_text(text, reply_markup=keyboard, parse_mode="Markdown")
    return CHOOSING_LEVEL


async def _show_unavailable(query) -> None:
    try:
        await query.answer("Курс устарел или сейчас недоступен.", show_alert=True)
    except Exception:
        pass
    try:
        await query.edit_message_text(
            "⚠️ Этот учебный модуль больше недоступен. Обнови меню.",
            reply_markup=_group_keyboard(),
        )
    except Exception:
        logger.debug("could not replace stale course callback", exc_info=True)


async def show_group_callback(update, context):
    del context
    query = update.callback_query
    data = str(query.data or "")
    prefix = "course_group:"
    if not data.startswith(prefix):
        await _show_unavailable(query)
        return ConversationHandler.END
    group_key = data[len(prefix):]
    groups = {group.key: group for group in list_groups(surface=SURFACE_TELEGRAM)}
    group = groups.get(group_key)
    courses = list_courses(surface=SURFACE_TELEGRAM, group=group_key) if group else []
    if group is None or not courses:
        await _show_unavailable(query)
        return ConversationHandler.END

    await query.answer()
    rows = [
        [InlineKeyboardButton(entry.title, callback_data=f"course:{entry.key}")]
        for entry in courses
    ]
    rows.append([InlineKeyboardButton("⬅️ К категориям", callback_data="course_menu")])
    await query.edit_message_text(
        f"{group.icon} *{group.title}*\n\nВыбери учебный модуль:",
        reply_markup=InlineKeyboardMarkup(rows),
        parse_mode="Markdown",
    )
    return ConversationHandler.END


async def course_menu_callback(update, context):
    query = update.callback_query
    await query.answer()
    return await choose_level(update, context, is_callback=True)


def _mode_keyboard(entry: CourseEntry) -> InlineKeyboardMarkup:
    rows = [
        [
            InlineKeyboardButton(
                _MODE_LABELS[mode],
                callback_data=f"course_mode:{mode}:{entry.key}",
            )
        ]
        for mode in entry.allowed_modes
    ]
    rows.append([
        InlineKeyboardButton(
            "⬅️ К категориям",
            callback_data="course_menu",
        )
    ])
    return InlineKeyboardMarkup(rows)


def _course_text(entry: CourseEntry) -> str:
    return (
        f"*{entry.title}*\n\n"
        f"{entry.description}\n"
        f"{_learning_note(entry)}\n"
        f"📝 {entry.default_question_count} вопросов\n\n"
        "Выбери режим прохождения:"
    )


async def start_course_deep_link(update, context, course_key: str) -> bool:
    """Handle one `/start <course>` token without consulting bot.py maps.

    ``False`` means the token is not a declared course and another deep-link
    owner may handle it. A declared-but-unavailable course is handled with a
    controlled fail-closed message and returns ``True``.
    """
    del context
    try:
        entry = resolve_course(course_key, surface=SURFACE_TELEGRAM)
        resolve_course_pool(entry)
    except UnknownCourseError:
        return False
    except (CourseCatalogError, KeyError):
        await update.message.reply_text(
            "⚠️ Этот учебный модуль сейчас недоступен. Открой /test для актуального меню.",
        )
        return True
    except Exception:
        logger.exception("Telegram course deep-link resolution failed")
        await update.message.reply_text(
            "⚠️ Не удалось безопасно открыть учебный модуль. Открой /test и попробуй ещё раз.",
        )
        return True

    await update.message.reply_text(
        _course_text(entry),
        reply_markup=_mode_keyboard(entry),
        parse_mode="Markdown",
    )
    return True


async def _show_course(query, course_key: str):
    try:
        entry = resolve_course(course_key, surface=SURFACE_TELEGRAM)
        # Resolve the pool here too; a course card must not be rendered if the
        # canonical registry changed or cannot provide the pool.
        resolve_course_pool(entry)
    except (CourseCatalogError, KeyError):
        await _show_unavailable(query)
        return ConversationHandler.END
    except Exception:
        logger.exception("Telegram course resolution failed")
        await _show_unavailable(query)
        return ConversationHandler.END

    await query.answer()
    await query.edit_message_text(
        _course_text(entry),
        reply_markup=_mode_keyboard(entry),
        parse_mode="Markdown",
    )
    return ConversationHandler.END


async def course_callback(update, context):
    del context
    query = update.callback_query
    data = str(query.data or "")
    prefix = "course:"
    if not data.startswith(prefix) or ":" in data[len(prefix):]:
        await _show_unavailable(query)
        return ConversationHandler.END
    return await _show_course(query, data[len(prefix):])


async def legacy_level_callback(update, context):
    """Validate stale deployed ``level_*`` buttons through the catalog."""
    del context
    query = update.callback_query
    key = str(query.data or "")
    return await _show_course(query, key)


async def legacy_confirm_level_callback(update, context):
    """Validate stale ``confirm_level_*`` buttons through the same catalog."""
    del context
    query = update.callback_query
    prefix = "confirm_level_"
    data = str(query.data or "")
    if not data.startswith(prefix):
        await _show_unavailable(query)
        return ConversationHandler.END
    return await _show_course(query, data[len(prefix):])


def _parse_mode_callback(data: str) -> tuple[str, str] | None:
    prefix = "course_mode:"
    if not data.startswith(prefix):
        return None
    parts = data[len(prefix):].split(":")
    if len(parts) != 2:
        return None
    mode, course_key = parts
    if mode not in _MODE_LIMITS or not course_key:
        return None
    return mode, course_key


def _parse_legacy_mode_callback(data: str) -> tuple[str, str] | None:
    for mode in _MODE_LIMITS:
        prefix = f"{mode}_mode_"
        if data.startswith(prefix):
            key = data[len(prefix):]
            return (mode, key) if key else None
    return None


async def _launch_course(update, context, *, mode: str, course_key: str):
    query = update.callback_query
    try:
        entry = resolve_course(
            course_key,
            surface=SURFACE_TELEGRAM,
            mode=mode,
        )
        pool = resolve_course_pool(entry)
    except (CourseCatalogError, KeyError):
        await _show_unavailable(query)
        return ConversationHandler.END
    except Exception:
        logger.exception("Telegram course start resolution failed")
        await _show_unavailable(query)
        return ConversationHandler.END

    # Reaching this point proves course existence, surface exposure, mode
    # eligibility, pool existence/size and server-side scoring policy. Callback
    # data contains no ranked/scoring toggle to escalate Chapter 2/3.
    count = entry.default_question_count
    if len(pool) < count:
        await _show_unavailable(query)
        return ConversationHandler.END
    questions = random.sample(pool, count)

    import telegram_controller as quiz

    # Acknowledge the click before a durable DB/session launch. If the launcher
    # reports an existing attempt or a retryable DB conflict, it may return None
    # after sending lifecycle guidance; the Telegram spinner must still stop.
    await query.answer()
    data = await quiz._launch_attempt(
        user=update.effective_user,
        bot=context.bot,
        chat_id=query.message.chat_id,
        mode="level",
        questions=questions,
        level_key=entry.pool_key,
        level_name=entry.title,
        time_limit=_MODE_LIMITS[mode],
    )
    if data is None:
        return ConversationHandler.END

    await query.edit_message_text(
        f"*{entry.title}*\n\n"
        f"📝 Вопросов: {len(questions)} · {_MODE_LABELS[mode]}\n"
        f"{_learning_note(entry)}\n"
        "Начинаем!",
        parse_mode="Markdown",
    )
    await quiz.send_question(context.bot, update.effective_user.id)
    return ANSWERING


async def course_mode_callback(update, context):
    parsed = _parse_mode_callback(str(update.callback_query.data or ""))
    if parsed is None:
        await _show_unavailable(update.callback_query)
        return ConversationHandler.END
    mode, course_key = parsed
    return await _launch_course(update, context, mode=mode, course_key=course_key)


async def legacy_mode_callback(update, context):
    """Validate stale deployed relaxed/timed/speed callbacks through catalog."""
    parsed = _parse_legacy_mode_callback(str(update.callback_query.data or ""))
    if parsed is None:
        await _show_unavailable(update.callback_query)
        return ConversationHandler.END
    mode, course_key = parsed
    return await _launch_course(update, context, mode=mode, course_key=course_key)


async def legacy_intro_start_callback(update, context):
    """Secure stale ``intro_start_level_introN`` callbacks as relaxed courses."""
    query = update.callback_query
    prefix = "intro_start_"
    data = str(query.data or "")
    if not data.startswith(prefix):
        await _show_unavailable(query)
        return ConversationHandler.END
    course_key = data[len(prefix):]
    if not course_key.startswith("level_intro"):
        await _show_unavailable(query)
        return ConversationHandler.END
    return await _launch_course(update, context, mode="relaxed", course_key=course_key)


__all__ = [
    "choose_level",
    "course_callback",
    "course_menu_callback",
    "course_mode_callback",
    "legacy_confirm_level_callback",
    "legacy_intro_start_callback",
    "legacy_level_callback",
    "legacy_level_config",
    "legacy_mode_callback",
    "show_group_callback",
    "start_course_deep_link",
]
