"""Chapter 4 reviewed-authoring runtime card surface for 1 Peter 4:1–19.

Research/source-depth provenance is intentionally not stored on runtime cards.
Each card carries only a stable product review-record link; the immutable v2
review registry owns Research SHA/digest/source-edge evidence.
"""

from __future__ import annotations

CHAPTER4_STAGING_QUESTIONS = [{'id': 'ch4_text_001',
  'review_record_id': 'ch4prv2_ch4_text_001_80e6ba918afa',
  'question': 'На чём основан призыв «вооружиться тем же намерением»?',
  'options': ['На готовности защищать общину силой при внешнем давлении',
              'На ожидании, что верность уменьшит вероятность дальнейшего страдания',
              'На страдании Христа во плоти как образце готовности верующих к страданию',
              'На мысли, что страдания верующих продолжают искупительное действие креста'],
  'correct': 2,
  'explanation': '4:1 связывает призыв с Христом, пострадавшим во плоти. Это образец готовности к верному страданию, а не физическому насилию или повторению искупления.',
  'verse': '1 Пет. 4:1',
  'topic': 'text',
  'domain': 'text',
  'claim_type': 'text',
  'confidence': 'high',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_gr_001',
  'review_record_id': 'ch4prv2_ch4_gr_001_7a87bf39c85e',
  'question': 'Что надёжно сообщает форма πέπαυται?',
  'options': ['Это perfect middle indicative, 3-е лицо ед. ч., от παύω',
              'Это aorist passive subjunctive от πάσχω',
              'Это perfect active imperative от παύω',
              'Это present middle participle от παύω'],
  'correct': 0,
  'explanation': 'MorphGNT разбирает πέπαυται как perfect middle indicative, 3-е лицо ед. ч., от παύω; сама форма не доказывает безгрешное совершенство.',
  'verse': '1 Пет. 4:1',
  'topic': 'morphology',
  'domain': 'morphology',
  'claim_type': 'greek',
  'confidence': 'high',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_text_002',
  'review_record_id': 'ch4prv2_ch4_text_002_dac12365508f',
  'question': 'Как 4:2 описывает ориентацию оставшегося времени «во плоти»?',
  'options': ['Как отказ от обычной городской и общественной жизни',
              'Как преимущественную сосредоточенность на молитве вместо повседневного труда',
              'Как сокращение контактов с неверующими ради жизни внутри общины',
              'Как жизнь не по человеческим желаниям, а по воле Божьей'],
  'correct': 3,
  'explanation': 'Оставшееся время во плоти противопоставлено жизни по человеческим желаниям и жизни по воле Божьей.',
  'verse': '1 Пет. 4:1-2',
  'topic': 'text',
  'domain': 'text',
  'claim_type': 'text',
  'confidence': 'high',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_text_003',
  'review_record_id': 'ch4prv2_ch4_text_003_f20fe1f7fba1',
  'question': 'Почему прежнее окружение удивляется верующим?',
  'options': ['Верующие заметно дистанцировались от прежнего общественного круга и его обычных занятий',
              'Верующие больше не участвуют с ними в том же потоке распутства',
              'Верующие стали добиваться нового публичного статуса и влияния',
              'Верующие изменили отношение к собственности и хозяйственной жизни'],
  'correct': 1,
  'explanation': 'Текст говорит о разрыве с прежним потоком распутства; конкретный юридический режим преследования из этого не следует.',
  'verse': '1 Пет. 4:4',
  'topic': 'text',
  'domain': 'text',
  'claim_type': 'text',
  'confidence': 'high',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_gr_002',
  'review_record_id': 'ch4prv2_ch4_gr_002_27449a0b3d6b',
  'question': 'Что морфология εὐηγγελίσθη фиксирует сама по себе?',
  'options': ['Aorist active indicative, 3-е лицо ед. ч., от εὐαγγελίζω',
              'Aorist passive indicative, 3-е лицо ед. ч., от εὐαγγελίζω',
              'Aorist passive subjunctive, 3-е лицо ед. ч., от εὐαγγελίζω',
              'Perfect passive indicative, 3-е лицо ед. ч., от εὐαγγελίζω'],
  'correct': 1,
  'explanation': 'MorphGNT фиксирует aorist passive indicative, 3-е лицо ед. ч., от εὐαγγελίζω; parsing не устанавливает хронологию, место или адресатов благовестия.',
  'verse': '1 Пет. 4:6',
  'topic': 'morphology',
  'domain': 'morphology',
  'claim_type': 'greek',
  'confidence': 'high',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_text_004',
  'review_record_id': 'ch4prv2_ch4_text_004_7a60693f9960',
  'question': 'Какова непосредственная реакция на «конец всего приблизился»?',
  'options': ['Определить вероятный календарный срок завершения истории',
              'Свернуть обычные обязанности ради напряжённого ожидания знамений',
              'Связать ближайшие политические потрясения с исполнением эсхатологического ожидания',
              'Быть здравомыслящими и трезвыми ради молитв'],
  'correct': 3,
  'explanation': 'Пётр переводит эсхатологическую близость в трезвость, здравомыслие и молитву, а не в вычисление дат.',
  'verse': '1 Пет. 4:7',
  'topic': 'text',
  'domain': 'text',
  'claim_type': 'text',
  'confidence': 'high',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_text_005',
  'review_record_id': 'ch4prv2_ch4_text_005_f196560668fb',
  'question': 'Что прямо говорит 4:8 о любви?',
  'options': ['Любовь покрывает множество грехов',
              'Любовь прежде всего предотвращает открытые конфликты в общине',
              'Любовь позволяет быстрее восстановить отношения без дальнейшего разбора проступка',
              'Любовь уменьшает последствия греха в отношениях между членами общины'],
  'correct': 0,
  'explanation': 'Прямое утверждение — любовь покрывает множество грехов; стих не отменяет истину, ответственность или защиту пострадавших.',
  'verse': '1 Пет. 4:8',
  'topic': 'text',
  'domain': 'text',
  'claim_type': 'text',
  'confidence': 'high',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_ot_001',
  'review_record_id': 'ch4prv2_ch4_ot_001_a50c79ff562d',
  'question': 'Как точнее описать словесное отношение 1 Пет. 4:8 к LXX Притч. 10:12?',
  'options': ['Это близкое дословное воспроизведение LXX с небольшой заменой одного слова',
              'Это самостоятельная христианская формула без заметной связи с пословичной традицией',
              'Связь с Притч. 10:12 серьёзна, но греческие формулировки различаются, поэтому это не дословная цитата LXX',
              'Это перевод той же строки прямо с еврейского текста, совпадающий с LXX по основной формулировке'],
  'correct': 2,
  'explanation': 'Связь с Притч. 10:12 серьёзна, однако формула 1 Петра отличается от LXX; поэтому безопаснее говорить о proverb reuse/background, а не о дословной цитате.',
  'verse': '1 Пет. 4:8 / Притч. 10:12',
  'topic': 'intertext',
  'domain': 'intertext',
  'claim_type': 'interpretation',
  'confidence': 'medium',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_text_006',
  'review_record_id': 'ch4prv2_ch4_text_006_1a633b5d8707',
  'question': 'Какой qualifier сопровождает гостеприимство?',
  'options': ['С готовностью принимать прежде всего признанных служителей',
              'С учётом того, может ли община предоставить отдельное место для гостя',
              'С ожиданием взаимности со стороны принимаемого',
              'Без ропота'],
  'correct': 3,
  'explanation': '4:9 требует взаимного гостеприимства без ропота.',
  'verse': '1 Пет. 4:9',
  'topic': 'text',
  'domain': 'text',
  'claim_type': 'text',
  'confidence': 'high',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_text_007',
  'review_record_id': 'ch4prv2_ch4_text_007_21aa15da10c7',
  'question': 'Кто должен служить полученным даром?',
  'options': ['Прежде всего пресвитеры как ответственные за общину',
              'Те, чьи дары публично распознаны общиной',
              'Каждый, в соответствии с полученным даром, служа друг другу',
              'Те, кто располагает материальными ресурсами для служения'],
  'correct': 2,
  'explanation': 'Пётр обращается к каждому получившему дар и связывает его с взаимным служением.',
  'verse': '1 Пет. 4:10',
  'topic': 'text',
  'domain': 'text',
  'claim_type': 'text',
  'confidence': 'high',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_gr_003',
  'review_record_id': 'ch4prv2_ch4_gr_003_475614d1b234',
  'question': 'Какое слово обозначает «огненное испытание»?',
  'options': ['κρίμα', 'πύρωσις (в тексте πυρώσει)', 'δόξα', 'οἰκονόμος'],
  'correct': 1,
  'explanation': 'В 4:12 употреблена форма πυρώσει от πύρωσις; лексема поддерживает образ огня/испытания, но сама не доказывает конкретный интертекст.',
  'verse': '1 Пет. 4:12',
  'topic': 'lexical',
  'domain': 'lexical',
  'claim_type': 'greek',
  'confidence': 'high',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_text_008',
  'review_record_id': 'ch4prv2_ch4_text_008_48451cb15551',
  'question': 'Как 4:13 описывает связь страданий верующих со страданиями Христа?',
  'options': ['Как участие в Его страданиях с перспективой будущей радости при явлении славы',
              'Как продолжение креста, которому приписывается сходная искупительная функция',
              'Как ожидаемый путь подтверждения верности через мученичество',
              'Как вклад верующих в завершение искупительного дела Христа'],
  'correct': 0,
  'explanation': 'Верующие радуются в мере участия в страданиях Христа с перспективой радости при явлении Его славы; их страдания не получают искупительной силы креста.',
  'verse': '1 Пет. 4:13',
  'topic': 'theology',
  'domain': 'theology',
  'claim_type': 'text',
  'confidence': 'high',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_text_009',
  'review_record_id': 'ch4prv2_ch4_text_009_1c864b85e921',
  'question': 'Какие виды страдания Пётр исключает из похвального страдания за Христа?',
  'options': ['Как убийца, вор, злодей или ἀλλοτριεπίσκοπος',
              'Страдание от болезни или иной телесной слабости',
              'Страдание, вызванное общественным осуждением',
              'Наказание за нарушение ритуальных норм'],
  'correct': 0,
  'explanation': '4:15 отличает страдание за Христа от последствий убийства, воровства, злодеяния и ἀλλοτριεπίσκοπος.',
  'verse': '1 Пет. 4:15',
  'topic': 'text',
  'domain': 'text',
  'claim_type': 'text',
  'confidence': 'high',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_text_010',
  'review_record_id': 'ch4prv2_ch4_text_010_b821eff88965',
  'question': 'Как должен реагировать страдающий «как христианин»?',
  'options': ['Скрывать христианскую идентичность',
              'Не стыдиться, а прославлять Бога в связи с этим именем',
              'Отвечать злословием на злословие',
              'Считать само страдание доказательством собственной безошибочности'],
  'correct': 1,
  'explanation': 'Пётр противопоставляет стыд прославлению Бога в связи с именем христианина.',
  'verse': '1 Пет. 4:16',
  'topic': 'text',
  'domain': 'text',
  'claim_type': 'text',
  'confidence': 'high',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_ot_002',
  'review_record_id': 'ch4prv2_ch4_ot_002_fb61f489fa4f',
  'question': 'Что показывает прямое сравнение 1 Пет. 4:18 с LXX Притч. 11:31?',
  'options': ['Преимущественно тематическое сходство при ограниченном словесном совпадении',
              'Сходство с другой строкой Притч при иной последовательности слов',
              'Очень близкое воспроизведение греческой последовательности и формулировки',
              'Совпадение ключевого слова δίκαιος при существенно независимой остальной строке'],
  'correct': 2,
  'explanation': '4:18 очень близко воспроизводит греческую последовательность LXX Притч. 11:31.',
  'verse': '1 Пет. 4:18 / Притч. 11:31 LXX',
  'topic': 'intertext',
  'domain': 'intertext',
  'claim_type': 'text',
  'confidence': 'high',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_theol_001',
  'review_record_id': 'ch4prv2_ch4_theol_001_81d75bc6ea50',
  'question': 'Какой необычный титул Бога выделяется в 4:19?',
  'options': ['ἀρχιποίμενος — Главный Пастырь',
              'ἀντίδικος — противник',
              'οἰκονόμος — домостроитель',
              'πιστὸς κτίστης — верный Творец'],
  'correct': 3,
  'explanation': 'В 4:19 Бог назван πιστὸς κτίστης — верным Творцом.',
  'verse': '1 Пет. 4:19',
  'topic': 'theology',
  'domain': 'theology',
  'claim_type': 'text',
  'confidence': 'high',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_disputed_001',
  'review_record_id': 'ch4prv2_ch4_disputed_001_2899e0f18de7',
  'question': 'Какой вывод о πέπαυται ἁμαρτίας удерживает границу между грамматикой и экзегезой?',
  'options': ['Perfect сам по себе устанавливает состояние безгрешности после перенесённого страдания',
              'Контекст поддерживает решительный разрыв с прежней греховной жизнью, но morphology сама не устанавливает sinless perfection',
              'Genitive ἁμαρτίας здесь лучше объяснять как наказание за чужую вину',
              'Значение конструкции следует определять по παύω без существенной роли контекста 4:2'],
  'correct': 1,
  'explanation': 'Контекст 4:1–2 поддерживает решительный разрыв с прежней греховной жизнью; грамматическая форма πέπαυται не превращает страдание в механизм безгрешного совершенства.',
  'verse': '1 Пет. 4:1',
  'topic': 'disputed',
  'domain': 'disputed',
  'claim_type': 'interpretation',
  'confidence': 'medium',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_syn_001',
  'review_record_id': 'ch4prv2_ch4_syn_001_bcb4cedc38b6',
  'question': 'Какую функцию ἐν ᾧ в 4:4 аргументирует Atkinson?',
  'options': ['Временную: «когда это происходит»',
              'Референциальную: «в отношении этого»',
              'Локативную: «в той сфере, где это происходит»',
              'Причинную: они злословят потому, что верующие больше не участвуют в прежнем образе жизни'],
  'correct': 3,
  'explanation': 'Atkinson аргументирует причинную функцию ἐν ᾧ в 4:4; это passage-level анализ, а не универсальная глосса для конструкции.',
  'verse': '1 Пет. 4:4',
  'topic': 'syntax',
  'domain': 'syntax',
  'claim_type': 'interpretation',
  'confidence': 'medium',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_disputed_002',
  'review_record_id': 'ch4prv2_ch4_disputed_002_fcb014fe2e70',
  'question': 'Какой вопрос о νεκροῖς в 4:6 остаётся за пределами одной морфологии?',
  'options': ['Были ли адресаты уже мертвы при благовестии или умерли позднее, и где происходило возвещение',
              'Что νεκροῖς имеет форму множественного числа',
              'Что νεκροῖς стоит в дательном падеже',
              'Что ближайший контекст упоминает суд живых и мёртвых'],
  'correct': 0,
  'explanation': 'Морфология νεκροῖς не выбирает хронологию или место благовестия и не идентифицирует адресатов; эти вопросы остаются экзегетическими.',
  'verse': '1 Пет. 4:6',
  'topic': 'disputed',
  'domain': 'disputed',
  'claim_type': 'interpretation',
  'confidence': 'contested',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_course_001',
  'review_record_id': 'ch4prv2_ch4_course_001_80c8a33b3664',
  'question': 'Как должен быть помечен выбранный курсом вариант толкования 1 Пет. 4:6?',
  'options': ['Как преобладающее нейтральное толкование, не требующее отдельной маркировки',
              'Как вывод, непосредственно требуемый дательным νεκροῖς',
              'Как позиция курса: благовестие было услышано при жизни, а адресаты уже умерли к моменту письма; нейтральный спор сохраняется',
              'Как основание для общей схемы посмертного второго шанса'],
  'correct': 2,
  'explanation': 'Выбранное чтение должно оставаться видимой [Позиция курса]: оно понимает «мёртвых» как людей, услышавших Евангелие при жизни и умерших позднее, при сохранении серьёзной postmortem alternative.',
  'verse': '1 Пет. 4:6',
  'topic': 'course_position',
  'domain': 'course_position',
  'claim_type': 'interpretation',
  'confidence': 'contested',
  'position': 'project',
  'competitive': False},
 {'id': 'ch4_disputed_003',
  'review_record_id': 'ch4prv2_ch4_disputed_003_4a2a0d0e2cb6',
  'question': 'Какой статус имеет отождествление благовестия «мёртвым» в 4:6 с провозглашением «духам» в 3:19?',
  'options': ['Это естественное следствие общей темы суда в соседних отрывках',
              'Это наиболее прямое значение различающихся глаголов εὐαγγελίζω и κηρύσσω',
              'Это отдельная интерпретационная гипотеза об адресатах, времени и событии, которую формулировки сами по себе не устанавливают',
              'Это синтаксический вывод из дательного νεκροῖς в 4:6'],
  'correct': 2,
  'explanation': 'Связь 4:6 с 3:19 можно аргументировать, но тождество адресатов, времени и события остаётся интерпретационной гипотезой; morphology не решает этот вопрос.',
  'verse': '1 Пет. 4:6 / 3:19',
  'topic': 'disputed',
  'domain': 'disputed',
  'claim_type': 'interpretation',
  'confidence': 'contested',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_course_002',
  'review_record_id': 'ch4prv2_ch4_course_002_a7d037defc3c',
  'question': 'Какую границу нужно соблюдать, используя ἤγγικεν в систематической эсхатологии?',
  'options': ['Форма поддерживает идею близости, но выбор полной эсхатологической системы требует более широкого канонического аргумента',
              'Perfect делает акцент на завершённости и тем самым преимущественно поддерживает preterist reading',
              'Близость в 4:7 лучше читать как указание на определённую последовательность будущих событий',
              'Форму следует трактовать через систематическую схему, а не через её грамматическое значение'],
  'correct': 0,
  'explanation': 'ἤγγικεν важно для текста и идеи близости, но не кодирует самостоятельно preterism, futurism или timing rapture; систематический вывод курса должен маркироваться отдельно.',
  'verse': '1 Пет. 4:7',
  'topic': 'course_position',
  'domain': 'course_position',
  'claim_type': 'interpretation',
  'confidence': 'medium',
  'position': 'project',
  'competitive': False},
 {'id': 'ch4_disputed_004',
  'review_record_id': 'ch4prv2_ch4_disputed_004_3fdeec15fc2a',
  'question': 'Какое применение формулы «любовь покрывает множество грехов» выходит за пределы 4:8?',
  'options': ['Связывать интенсивную любовь с терпением к проступкам внутри общины',
              'Рассматривать любовь как ресурс для восстановления отношений',
              'Учитывать взаимный общинный контекст при практическом применении',
              'Использовать «покрывает» как основание обходить покаяние, защиту пострадавших, ответственность или справедливость'],
  'correct': 3,
  'explanation': 'Пословичная формула поддерживает forgiving/forbearing love, но не даёт основания скрывать зло, отменять покаяние, защиту пострадавших или ответственность.',
  'verse': '1 Пет. 4:8',
  'topic': 'application',
  'domain': 'application',
  'claim_type': 'interpretation',
  'confidence': 'medium',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_hist_001',
  'review_record_id': 'ch4prv2_ch4_hist_001_53267291f181',
  'question': 'Какой исторический вывод о гостеприимстве 4:9 проходит evidence boundary?',
  'options': ['Императив отражает существование специализированных помещений общины для путешественников',
              'Домашнее гостеприимство было важным ресурсом раннехристианской общины и миссии, но конкретную экономическую схему адресатов из стиха не восстановить',
              'Адресаты, вероятно, несли формальную обязанность содержать странствующих служителей',
              'Призыв прежде всего регулирует приём официальных посланников церкви'],
  'correct': 1,
  'explanation': 'Исторический фон подтверждает важность домашнего гостеприимства, но один императив 4:9 не восстанавливает конкретную юридическую или экономическую систему аудитории.',
  'verse': '1 Пет. 4:9',
  'topic': 'history',
  'domain': 'history',
  'claim_type': 'history',
  'confidence': 'medium',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_disputed_005',
  'review_record_id': 'ch4prv2_ch4_disputed_005_28157dfdbb55',
  'question': 'Что можно заключить из пары «говорит / служит» в 4:11?',
  'options': ['Пётр организует увещание вокруг говорения и служения, но не объявляет эту пару исчерпывающим каталогом даров',
              'Пара лучше всего читается как фиксированная двухчастная классификация духовных даров в общине',
              'Обе категории обозначают две формальные церковные должности',
              'Решающим для структуры служит сопоставление с более поздними Павловыми перечнями'],
  'correct': 0,
  'explanation': 'Говорение и служение структурируют увещание 4:11; из самой риторической пары не следует исчерпывающая таксономия духовных даров.',
  'verse': '1 Пет. 4:10-11',
  'topic': 'disputed',
  'domain': 'disputed',
  'claim_type': 'interpretation',
  'confidence': 'medium',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_course_003',
  'review_record_id': 'ch4prv2_ch4_course_003_5c9a14ba2778',
  'question': 'Как преподавать 4:10–11 в курсе, придерживающемся cessationism?',
  'options': ['Читать χάρισμα здесь преимущественно как немиракульный дар и использовать это как локальный аргумент',
              'Считать пару «говорит / служит» непосредственной двухчастной моделью cessationism',
              'Сначала преподавать наблюдаемый текст о дарах и служении, а cessationism маркировать как систематический вывод курса из более широкого корпуса',
              'Отделить систематическую позицию от этого отрывка настолько, чтобы она не могла обсуждаться рядом с ним'],
  'correct': 2,
  'explanation': 'Сам 4:10–11 не закрывает вопрос cessationism; курс может отстаивать эту систематическую позицию, но должен явно отличать её от passage-level наблюдения.',
  'verse': '1 Пет. 4:10-11',
  'topic': 'course_position',
  'domain': 'course_position',
  'claim_type': 'interpretation',
  'confidence': 'medium',
  'position': 'project',
  'competitive': False},
 {'id': 'ch4_disputed_006',
  'review_record_id': 'ch4prv2_ch4_disputed_006_6aba0ea2cb95',
  'question': 'Как лучше передать степень уверенности по ἀλλοτριεπίσκοπος в 4:15?',
  'options': ['Сузить значение к политическому «революционеру» как основной исторической реконструкции',
              'Сузить значение к «доносчику/осведомителю» как основной социальной роли',
              'Из-за редкости слова отказаться даже от общего значения вмешательства в чужие дела',
              'Meddling/interference family хорошо поддержана контекстом и Brown, но узкую социально-правовую реконструкцию нельзя выдавать за лексическую необходимость'],
  'correct': 3,
  'explanation': 'Исследование усиливает family «meddling/interference», но редкая лексема и ограниченный корпус не лицензируют чрезмерно узкую социально-правовую глоссу.',
  'verse': '1 Пет. 4:15',
  'topic': 'lexical',
  'domain': 'lexical',
  'claim_type': 'interpretation',
  'confidence': 'contested',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_hist_002',
  'review_record_id': 'ch4prv2_ch4_hist_002_899cff312f3a',
  'question': 'Что термин Χριστιανός в 4:16 даёт историческому анализу — и чего не даёт?',
  'options': ['Он показывает формальную юридическую категорию, из которой можно восстановить процедуру преследования',
              'Он подтверждает социальную идентификацию христиан, но сам по себе не устанавливает конкретную общеимперскую политику или точную дату',
              'Он лучше всего привязывает письмо к Неронову преследованию',
              'Он функционирует как внутреннее самообозначение и потому мало пригоден для социальной истории'],
  'correct': 1,
  'explanation': 'Χριστιανός — важный datum социальной идентификации, но одного ярлыка недостаточно, чтобы выбрать конкретный императорский режим или точную дату письма.',
  'verse': '1 Пет. 4:16',
  'topic': 'history',
  'domain': 'history',
  'claim_type': 'history',
  'confidence': 'medium',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_tc_001',
  'review_record_id': 'ch4prv2_ch4_tc_001_2b6fdab335b1',
  'question': 'Как корректно сформулировать reading 4:16 без edition flattening?',
  'options': ['SBLGNT и ECM/NA28 дают ὀνόματι; различие относится главным образом к пунктуации',
              'SBLGNT печатает ὀνόματι, тогда как ECM/NA28 принимает μέρει; учебная формулировка должна называть текстовую базу',
              'μέρει относится к переводческой традиции, а не к греческому критическому тексту',
              'ὀνόματι следует называть исходным чтением, а μέρει — редакционной перефразировкой ECM'],
  'correct': 1,
  'explanation': 'В узле 4:16 SBLGNT и ECM/NA28 печатают разные чтения; безопасная формулировка называет издание и не превращает один text-base в абстрактный «греческий текст».',
  'verse': '1 Пет. 4:16',
  'topic': 'textual_criticism',
  'domain': 'textual_criticism',
  'claim_type': 'text',
  'confidence': 'high',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_tc_002',
  'review_record_id': 'ch4prv2_ch4_tc_002_b04af18fa177',
  'question': 'Какую роль играет CBGM/ECM reasoning в узле ὀνόματι / μέρει?',
  'options': ['Приоритет получает чтение с более многочисленной внешней поддержкой',
              'Приоритет получает чтение, которое легче объяснить как более длинную форму',
              'CBGM заменяет редакционное суждение вычисленным генеалогическим результатом',
              'Решение учитывает внешние данные, genealogical coherence, происхождение вариантов и редакционное суждение'],
  'correct': 3,
  'explanation': 'ECM/CBGM не сводит решение к majority/oldest/longer-reading rule и не отменяет редакционного суждения; это важно для 4:16.',
  'verse': '1 Пет. 4:16',
  'topic': 'textual_criticism',
  'domain': 'textual_criticism',
  'claim_type': 'interpretation',
  'confidence': 'medium',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_ot_003',
  'review_record_id': 'ch4prv2_ch4_ot_003_556ed64f27ba',
  'question': 'Как следует преподавать предложенную связь Мал. 3 с 1 Пет. 4:12–19?',
  'options': ['Как установленную формальную цитату, задающую литературную структуру всего отрывка',
              'Как слабую случайную аналогию, не имеющую заметной исследовательской поддержки',
              'Как серьёзно предложенный prophetic/imagery background; степень зависимости спорна, а formal/sustained quotation не установлена',
              'Как основной пророческий источник, через который следует объяснять весь блок 4:12–19'],
  'correct': 2,
  'explanation': 'Malachi 3 имеет серьёзную историю как предложенный background, но степень зависимости спорна; formal/exclusive quotation не установлена, и существует альтернативная Zechariah proposal.',
  'verse': '1 Пет. 4:12-19 / Мал. 3',
  'topic': 'intertext',
  'domain': 'intertext',
  'claim_type': 'interpretation',
  'confidence': 'contested',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_ot_004',
  'review_record_id': 'ch4prv2_ch4_ot_004_e1e84322ba70',
  'question': 'Чем связь 4:18 с LXX Притч. 11:31 отличается от более свободного proverb reuse в 4:8?',
  'options': ['4:18 значительно плотнее воспроизводит греческую последовательность и формулировку LXX Притч. 11:31',
              '4:18 сохраняет в основном тему, но заметно перестраивает греческую строку',
              '4:18 лучше объясняется самостоятельным переводом еврейского текста без опоры на LXX',
              '4:18 выглядит как поздняя гармонизация к Притчам, а не как часть текста письма'],
  'correct': 0,
  'explanation': 'Греческое совпадение 4:18 с LXX Притч. 11:31 очень плотное и допускает quotation-level description; это сильнее более свободной связи 4:8 с Притч. 10:12.',
  'verse': '1 Пет. 4:18 / Притч. 11:31 LXX',
  'topic': 'intertext',
  'domain': 'intertext',
  'claim_type': 'interpretation',
  'confidence': 'high',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_gr_004',
  'review_record_id': 'ch4prv2_ch4_gr_004_d612568d70fc',
  'question': 'Как MorphGNT разбирает ὁπλίσασθε?',
  'options': ['Aorist middle imperative, 2-е лицо мн. ч., от ὁπλίζομαι',
              'Present active indicative, 2-е лицо мн. ч.',
              'Perfect passive participle, nominative plural',
              'Aorist active infinitive'],
  'correct': 0,
  'explanation': 'ὁπλίσασθε — aorist middle imperative, 2-е лицо мн. ч.; parsing не определяет весь смысл метафоры.',
  'verse': '1 Пет. 4:1',
  'topic': 'morphology',
  'domain': 'morphology',
  'claim_type': 'greek',
  'confidence': 'high',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_text_011',
  'review_record_id': 'ch4prv2_ch4_text_011_a74f241e3642',
  'question': 'Как Пётр оценивает время, уже проведённое в прежнем языческом образе жизни?',
  'options': ['Его нужно воспринимать как необходимый этап духовного опыта',
              'Его достаточно; возвращаться к прежнему образу жизни не следует',
              'Оно служит главным образом фоном и мало связано с нынешним поведением',
              'Vice list описывает репрезентативную биографию адресатов, а не риторический контраст'],
  'correct': 1,
  'explanation': '4:3 говорит, что прошедшего времени достаточно; vice list не является персональным досье каждого адресата.',
  'verse': '1 Пет. 4:3',
  'topic': 'text',
  'domain': 'text',
  'claim_type': 'text',
  'confidence': 'high',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_text_012',
  'review_record_id': 'ch4prv2_ch4_text_012_04d6fa5fcfee',
  'question': 'Перед кем, по 4:5, противники дадут отчёт?',
  'options': ['Перед местным правителем', 'Перед апостолами', 'Перед Тем, Кто готов судить живых и мёртвых', 'Перед умершими членами общины'],
  'correct': 2,
  'explanation': 'Текст говорит о Божественном Судье живых и мёртвых; точную дату суда он здесь не задаёт.',
  'verse': '1 Пет. 4:5',
  'topic': 'text',
  'domain': 'text',
  'claim_type': 'text',
  'confidence': 'high',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_gr_005',
  'review_record_id': 'ch4prv2_ch4_gr_005_c264a78984e4',
  'question': 'Как MorphGNT разбирает ἤγγικεν?',
  'options': ['Aorist passive imperative',
              'Present middle participle',
              'Future active indicative',
              'Perfect active indicative, 3-е лицо ед. ч., от ἐγγίζω'],
  'correct': 3,
  'explanation': 'ἤγγικεν — perfect active indicative, 3-е лицо ед. ч.; систематическая эсхатология требует большего, чем parsing.',
  'verse': '1 Пет. 4:7',
  'topic': 'morphology',
  'domain': 'morphology',
  'claim_type': 'greek',
  'confidence': 'high',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_lex_001',
  'review_record_id': 'ch4prv2_ch4_lex_001_c5f7007107e1',
  'question': 'Как верующие названы в связи с многообразной Божьей благодатью?',
  'options': ['καλοὶ οἰκονόμοι — добрые распорядители',
              'ἀρχιποίμενες — главные пастыри',
              'ἀντίδικοι — противники',
              'κριταί — судьи'],
  'correct': 0,
  'explanation': '4:10 называет их καλοὶ οἰκονόμοι; метафора stewardship сама не учреждает отдельную должность.',
  'verse': '1 Пет. 4:10',
  'topic': 'lexical',
  'domain': 'lexical',
  'claim_type': 'greek',
  'confidence': 'high',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_theol_002',
  'review_record_id': 'ch4prv2_ch4_theol_002_f0958fe91e94',
  'question': 'Какова конечная цель говорения и служения в 4:10–11?',
  'options': ['Чтобы выделить более духовных членов общины',
              'Чтобы во всём прославлялся Бог через Иисуса Христа',
              'Чтобы установить исчерпывающий каталог даров',
              'Чтобы служащие получили общественный статус'],
  'correct': 1,
  'explanation': 'Дары направлены на служение другим из Божьих ресурсов, чтобы во всём прославлялся Бог через Иисуса Христа.',
  'verse': '1 Пет. 4:10-11',
  'topic': 'theology',
  'domain': 'theology',
  'claim_type': 'interpretation',
  'confidence': 'medium',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_text_013',
  'review_record_id': 'ch4prv2_ch4_text_013_de343753c5d4',
  'question': 'Как верующим следует относиться к «огненному испытанию»?',
  'options': ['Как к признаку того, что Божье благоволение ослабло',
              'Как к несчастью, не связанному с христианской верностью',
              'Не удивляться ему как чему-то чуждому',
              'Как к подтверждению особого духовного статуса страдающего'],
  'correct': 2,
  'explanation': 'Пётр прямо говорит не удивляться испытанию как странному событию.',
  'verse': '1 Пет. 4:12',
  'topic': 'text',
  'domain': 'text',
  'claim_type': 'text',
  'confidence': 'high',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_tc_003',
  'review_record_id': 'ch4prv2_ch4_tc_003_903a331d3ce8',
  'question': 'Как current ECM-based textual criticism оценивает расширение с δύναμις в 4:14?',
  'options': ['Расширение следует предпочесть из-за его наличия в Sinaiticus',
              'Рукописная традиция в целом склоняется к расширению без существенного текстового узла',
              'Текущая опубликованная критическая работа не позволяет отдать предпочтение одному чтению',
              'Краткое чтение предпочтительно; расширение древнее и реально засвидетельствовано, но рассматривается как вторичное'],
  'correct': 3,
  'explanation': 'Wave 3n closure опирается на Williams–Horrell с прямой ссылкой на ECM 182 и независимую опубликованную ECM comparison; это current critical decision, не manuscript unanimity.',
  'verse': '1 Пет. 4:14',
  'topic': 'textual_criticism',
  'domain': 'textual_criticism',
  'claim_type': 'text',
  'confidence': 'high',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_theol_003',
  'review_record_id': 'ch4prv2_ch4_theol_003_4a3042af3eca',
  'question': 'Откуда, по 4:17, начинается κρίμα?',
  'options': ['От дома Божьего', 'От языческих храмов', 'От римской администрации', 'От ангельского мира'],
  'correct': 0,
  'explanation': 'Прямой текст говорит о начале суда от дома Божьего; конкретный prophetic background — отдельный вопрос.',
  'verse': '1 Пет. 4:17',
  'topic': 'theology',
  'domain': 'theology',
  'claim_type': 'text',
  'confidence': 'high',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_app_001',
  'review_record_id': 'ch4prv2_ch4_app_001_77050f91880a',
  'question': 'Как 4:19 соединяет доверие Богу и действие?',
  'options': ['Доверие Богу ведёт к отказу от значимой инициативы во время страдания',
              'Страдающие вверяют себя верному Творцу, продолжая делать добро',
              'Делание добра становится практической альтернативой самому акту доверия',
              'Страдание смещает этическую ответственность на обстоятельства'],
  'correct': 1,
  'explanation': 'Доверие верному Творцу соединено с продолжающимся деланием добра; это активная верность, не пассивность.',
  'verse': '1 Пет. 4:19',
  'topic': 'application',
  'domain': 'application',
  'claim_type': 'application',
  'confidence': 'medium',
  'position': 'project',
  'competitive': False},
 {'id': 'ch4_syn_002',
  'review_record_id': 'ch4prv2_ch4_syn_002_1b894d84fed9',
  'question': 'Какая цель объединяет говорение и служение в конце 4:11?',
  'options': ['Чтобы говорение и служение обозначали два официальных церковных чина',
              'Чтобы речь говорящего воспринималась как богодухновенное изречение',
              'Чтобы во всём прославлялся Бог через Иисуса Христа',
              'Чтобы служение подтверждало особый общественный статус служащего'],
  'correct': 2,
  'explanation': 'ἵνα ... δοξάζηται задаёт God-glorifying purpose для говорения и служения.',
  'verse': '1 Пет. 4:11',
  'topic': 'syntax',
  'domain': 'syntax',
  'claim_type': 'text',
  'confidence': 'high',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_gr_006',
  'review_record_id': 'ch4prv2_ch4_gr_006_9656be87869f',
  'question': 'Как MorphGNT разбирает ἀναπαύεται в 4:14?',
  'options': ['Aorist active imperative',
              'Perfect passive participle',
              'Future middle indicative',
              'Present middle indicative, 3-е лицо ед. ч., от ἀναπαύω'],
  'correct': 3,
  'explanation': 'MorphGNT размечает ἀναπαύεται как present middle indicative, 3-е лицо ед. ч.; parsing не решает вариантное расширение стиха.',
  'verse': '1 Пет. 4:14',
  'topic': 'morphology',
  'domain': 'morphology',
  'claim_type': 'greek',
  'confidence': 'high',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_hist_003',
  'review_record_id': 'ch4prv2_ch4_hist_003_03fe859a9125',
  'question': 'Почему 4:3 поддерживает преимущественно языческое прошлое аудитории, но не доказывает это для каждого адресата?',
  'options': ['Vice list и идолослужения сильно поддерживают predominantly Gentile background, но риторика общины не устанавливает биографию каждого человека',
              'Потому что этнический статус прямо обозначен рядом с описанием каждого адресата',
              'Потому что сходный набор практик широко засвидетельствован и среди иудейских общин',
              'Потому что этническое происхождение предпочтительно выводить из внешних источников, а не из риторики письма'],
  'correct': 0,
  'explanation': 'Stenschke считает 4:3 сильным указанием на predominantly Gentile audience, но это не 100%-ная персональная биография каждого адресата.',
  'verse': '1 Пет. 4:3',
  'topic': 'history',
  'domain': 'history',
  'claim_type': 'history',
  'confidence': 'medium',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_hist_004',
  'review_record_id': 'ch4prv2_ch4_hist_004_1150f1da19e1',
  'question': 'Почему страдания 4:12–16 нельзя автоматически привязать к одному общеимперскому официальному гонению?',
  'options': ['Потому что описание страданий лучше понимать как социальное давление без физической опасности',
              'Потому что существуют конкурирующие исторические реконструкции, а текст сам не выбирает один имперский режим без дополнительных данных',
              'Потому что термин Χριστιανός лучше всего привязывает текст к эпохе Траяна',
              'Потому что описание 4:12–16 содержит достаточно признаков для довольно точной имперской датировки'],
  'correct': 1,
  'explanation': 'Byrley картирует конкурирующие Nero/Domitian/Trajan/local-social модели; осторожность не равна отрицанию всякой официальной угрозы.',
  'verse': '1 Пет. 4:12-16',
  'topic': 'history',
  'domain': 'history',
  'claim_type': 'history',
  'confidence': 'contested',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_lex_002',
  'review_record_id': 'ch4prv2_ch4_lex_002_4618aaa04447',
  'question': 'Что λόγια θεοῦ подчёркивает в 4:11, не превращая каждую речь христианина в Писание?',
  'options': ['Что речь, произнесённая в этом режиме, получает статус канонического слова',
              'Что формула описывает общую полезность речи без особой связи с Божьим словом',
              'Oracle/divine-utterance lexical background и ответственность говорить как Божьи изречения, без вывода о каноничности каждой речи',
              'Что эта формула ограничивает говорение авторами Писания или официальными пророками'],
  'correct': 2,
  'explanation': 'Лексический фон λόγιον сильнее «хороших слов», но ὡς λόγια θεοῦ не канонизирует каждую человеческую речь.',
  'verse': '1 Пет. 4:11',
  'topic': 'lexical',
  'domain': 'lexical',
  'claim_type': 'greek',
  'confidence': 'medium',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_tc_004',
  'review_record_id': 'ch4prv2_ch4_tc_004_3fbdf0e27d8e',
  'question': 'Какое заметное расширение имеет Codex Sinaiticus в 4:14 по сравнению с SBLGNT?',
  'options': ['Он заменяет Χριστοῦ на Πέτρου',
              'Он опускает выражение о Духе славы',
              'Он имеет в этом стихе вариант μέρει вместо ὀνόματι',
              'Он включает καὶ τῆς δυνάμεως αὐτοῦ'],
  'correct': 3,
  'explanation': 'Sinaiticus включает καὶ τῆς δυνάμεως αὐτοῦ. Это named-manuscript fact; один свидетель не решает Ausgangstext.',
  'verse': '1 Пет. 4:14',
  'topic': 'textual_criticism',
  'domain': 'textual_criticism',
  'claim_type': 'text',
  'confidence': 'high',
  'position': 'neutral',
  'competitive': False},
 {'id': 'ch4_app_002',
  'review_record_id': 'ch4prv2_ch4_app_002_a9c6e648d728',
  'question': 'Как применять призыв «вооружиться тем же намерением», не превращая страдание в духовную заслугу?',
  'options': ['Готовиться оставаться верным Божьей воле даже при страдании; страдание не покупает прощение и не делает человека святым само по себе',
              'Искать страдание как средство подтвердить духовную заслугу',
              'Считать физическую боль важным показателем более высокой святости',
              'Снижать риск страдания даже тогда, когда это требует компромисса с верностью'],
  'correct': 0,
  'explanation': 'Project application — готовность к верности в страдании, без мериторной теологии страдания.',
  'verse': '1 Пет. 4:1-2',
  'topic': 'application',
  'domain': 'application',
  'claim_type': 'application',
  'confidence': 'medium',
  'position': 'project',
  'competitive': False},
 {'id': 'ch4_app_003',
  'review_record_id': 'ch4prv2_ch4_app_003_175900c71ab1',
  'question': 'Как применять «любовь покрывает множество грехов» без сокрытия зла?',
  'options': ['Любовь предполагает избегать открытого обличения зла ради сохранения мира',
              'Практиковать прощение и терпение, не отменяя истину, покаяние, защиту пострадавших, ответственность и правосудие',
              'Любовь обычно предпочитает внутреннее урегулирование обращению за законной защитой',
              'Формула о покрытии делает церковную дисциплину второстепенной в подобных случаях'],
  'correct': 1,
  'explanation': 'Курс отделяет forgiving love от concealment/impunity; стих нельзя использовать для сокрытия преступления или насилия.',
  'verse': '1 Пет. 4:8',
  'topic': 'application',
  'domain': 'application',
  'claim_type': 'application',
  'confidence': 'medium',
  'position': 'project',
  'competitive': False},
 {'id': 'ch4_app_004',
  'review_record_id': 'ch4prv2_ch4_app_004_fb2f4bbc207e',
  'question': 'Как 4:10–11 противостоит превращению духовных даров в личный статус?',
  'options': ['Дар даёт право на неподотчётное превосходство',
              'Главная цель дара — личный бренд',
              'Дар — полученная благодать для служения другим из Божьей силы, с целью Божьей славы',
              'Дар освобождает от обычной ответственности перед общиной'],
  'correct': 2,
  'explanation': 'Stewardship language направляет дар вовне — к служению другим и Божьей славе, а не к самоутверждению.',
  'verse': '1 Пет. 4:10-11',
  'topic': 'application',
  'domain': 'application',
  'claim_type': 'application',
  'confidence': 'medium',
  'position': 'project',
  'competitive': False},
 {'id': 'ch4_app_005',
  'review_record_id': 'ch4prv2_ch4_app_005_88e2cb86ca38',
  'question': 'Как отличать страдание «как христианин» от последствий собственного зла?',
  'options': ['Негативную общественную реакцию на христианина следует прежде всего трактовать как гонение',
              'Главным критерием считать самоописание человека «я христианин»',
              'Пётр здесь не связывает качество страдания с поведением самого страдающего',
              'Пётр прямо отличает поношение за имя Христа от страдания как убийца, вор, злодей или нарушитель; не всякое негативное последствие — гонение за праведность'],
  'correct': 3,
  'explanation': 'Application следует прямому разграничению 4:14–16 и не использует язык преследования для ухода от ответственности.',
  'verse': '1 Пет. 4:12-16',
  'topic': 'application',
  'domain': 'application',
  'claim_type': 'application',
  'confidence': 'medium',
  'position': 'project',
  'competitive': False}]


def answer_position_counts(items: list[dict] | None = None) -> dict[int, int]:
    counts = {0: 0, 1: 0, 2: 0, 3: 0}
    for item in items or CHAPTER4_STAGING_QUESTIONS:
        counts[int(item["correct"])] += 1
    return counts


__all__ = ["CHAPTER4_STAGING_QUESTIONS", "answer_position_counts"]
