"""MorphGNT-backed Greek observations for 1 Peter 3:13-17."""

GREEK_3_13_17 = [
    {
        "id": "ch3_gr_301",
        "question": "Как MorphGNT разбирает ἁγιάσατε в 1 Пет. 3:15?",
        "options": ["Аорист, актив, императив, 2-е лицо мн. числа", "Настоящее активное, инфинитив", "Перфект пассив, причастие", "Аорист пассив, 3-е лицо"],
        "correct": 0,
        "explanation": "MorphGNT: ἁγιάσατε = V- 2AAD-P--, aorist active imperative, 2nd plural, от ἁγιάζω. Это морфология; адресат повеления и его богословское значение анализируются отдельно.",
        "verse": "1 Пет. 3:15", "topic": "Greek: ἁγιάσατε", "claim_type": "greek", "confidence": "high", "position": "neutral", "competitive": False,
        "sources": ["sblgnt", "morphgnt_1peter"],
    },
    {
        "id": "ch3_gr_302",
        "question": "Что морфологически общего у κύριον и τὸν Χριστόν?",
        "options": ["Оба — accusative masculine singular", "Оба — genitive plural", "Оба — глаголы", "Оба — dative feminine"],
        "correct": 0,
        "explanation": "κύριον = N- ----ASM-, Χριστόν = N- ----ASM-, τὸν = RA ----ASM-. Морфология не решает спор о предикативном или аппозиционном анализе κύριον и сама по себе не является христологическим выводом.",
        "verse": "1 Пет. 3:15", "topic": "Greek: κύριον τὸν Χριστόν", "claim_type": "greek", "confidence": "high", "position": "neutral", "competitive": False,
        "sources": ["sblgnt", "morphgnt_1peter"],
    },
    {
        "id": "ch3_gr_303",
        "question": "Как устроено ἕτοιμοι ἀεί?",
        "options": ["ἕτοιμοι — adjective nominative masculine plural; ἀεί — adverb", "Оба — императивы", "ἕτοιμοι — инфинитив", "Оба — генитивы"],
        "correct": 0,
        "explanation": "ἕτοιμοι = A- ----NPM-, ἀεί = D- --------. Форма выражает постоянную готовность, не команду превращать каждое общение в спор.",
        "verse": "1 Пет. 3:15", "topic": "Greek: ἕτοιμοι ἀεί", "claim_type": "greek", "confidence": "high", "position": "neutral", "competitive": False,
        "sources": ["sblgnt", "morphgnt_1peter"],
    },
    {
        "id": "ch3_gr_304",
        "question": "Какова форма ἀπολογίαν в πρὸς ἀπολογίαν?",
        "options": ["Noun accusative feminine singular", "Aorist imperative", "Adjective nominative plural", "Participle dative singular"],
        "correct": 0,
        "explanation": "ἀπολογίαν = N- ----ASF-; πρός здесь с accusative. Лексически это защита/ответ в контексте требования ответа; одна форма не выбирает современную apologetics methodology.",
        "verse": "1 Пет. 3:15", "topic": "Greek: πρὸς ἀπολογίαν", "claim_type": "greek", "confidence": "high", "position": "neutral", "competitive": False,
        "sources": ["sblgnt", "morphgnt_1peter", "bdag_3"],
    },
    {
        "id": "ch3_gr_305",
        "question": "Как разбирается αἰτοῦντι в παντὶ τῷ αἰτοῦντι?",
        "options": ["Present active participle, dative masculine singular", "Aorist passive infinitive", "Perfect imperative", "Middle participle accusative plural"],
        "correct": 0,
        "explanation": "αἰτοῦντι = V- -PAPDSM-. παντί и τῷ также dative masculine singular: формула говорит о каждом спрашивающем, не только о названном судебном чиновнике.",
        "verse": "1 Пет. 3:15", "topic": "Greek: παντὶ τῷ αἰτοῦντι", "claim_type": "greek", "confidence": "high", "position": "neutral", "competitive": False,
        "sources": ["sblgnt", "morphgnt_1peter", "jobes_becnt_1peter_2022"],
    },
    {
        "id": "ch3_gr_306",
        "question": "Какие формы у λόγον и ἐλπίδος?",
        "options": ["λόγον — acc. masc. sg.; ἐλπίδος — gen. fem. sg.", "Оба — dative plural", "Оба — глаголы", "Оба — nominative"],
        "correct": 0,
        "explanation": "λόγον = N- ----ASM-, ἐλπίδος = N- ----GSF-. Запрашиваемый λόγος относится к надежде; конкретная позднейшая методология этими падежами не кодируется.",
        "verse": "1 Пет. 3:15", "topic": "Greek: λόγον / ἐλπίδος", "claim_type": "greek", "confidence": "high", "position": "neutral", "competitive": False,
        "sources": ["sblgnt", "morphgnt_1peter"],
    },
    {
        "id": "ch3_gr_307",
        "question": "Каковы формы πραΰτητος и φόβου после μετά?",
        "options": ["Оба genitive singular", "Оба accusative plural", "Глагол и наречие", "Оба императивы"],
        "correct": 0,
        "explanation": "πραΰτητος = N- ----GSF-, φόβου = N- ----GSM-. После μετά с genitive они описывают манеру ответа; точный прагматический оттенок φόβος определяется контекстом, не падежом.",
        "verse": "1 Пет. 3:15-16", "topic": "Greek: πραΰτης / φόβος", "claim_type": "greek", "confidence": "high", "position": "neutral", "competitive": False,
        "sources": ["sblgnt", "morphgnt_1peter", "bdag_3"],
    },
    {
        "id": "ch3_gr_308",
        "question": "Как разобрано συνείδησιν ἔχοντες ἀγαθήν?",
        "options": ["συνείδησιν/ἀγαθήν — acc. fem. sg.; ἔχοντες — present active participle nom. masc. pl.", "Все — глаголы", "συνείδησιν — genitive plural", "ἀγαθήν — adverb"],
        "correct": 0,
        "explanation": "συνείδησιν = N- ----ASF-, ἔχοντες = V- -PAPNPM-, ἀγαθήν = A- ----ASF-. Речевой ответ соседствует с требованием доброй совести.",
        "verse": "1 Пет. 3:16", "topic": "Greek: добрая совесть", "claim_type": "greek", "confidence": "high", "position": "neutral", "competitive": False,
        "sources": ["sblgnt", "morphgnt_1peter"],
    },
    {
        "id": "ch3_gr_309",
        "question": "Как MorphGNT разбирает θέλοι в 1 Пет. 3:17?",
        "options": ["Present active optative, 3rd singular", "Aorist imperative 2nd plural", "Perfect passive infinitive", "Present participle dative"],
        "correct": 0,
        "explanation": "θέλοι = V- 3PAO-S--. С εἰ это поддерживает условный характер оборота о Божьей воле; форма не решает всю проблему причинности и моральной ответственности за страдание.",
        "verse": "1 Пет. 3:17", "topic": "Greek: εἰ θέλοι", "claim_type": "greek", "confidence": "high", "position": "neutral", "competitive": False,
        "sources": ["sblgnt", "morphgnt_1peter", "achtemeier_hermeneia_1peter"],
    },
]

__all__ = ["GREEK_3_13_17"]
