"""MorphGNT-backed Greek observations for 1 Peter 3:13-17."""

GREEK_3_13_17 = [
    {
        "id": "ch3_gr_301",
        "question": "Как MorphGNT разбирает ἁγιάσατε в 1 Пет. 3:15?",
        "options": [
            "Aorist active imperative, 2nd person plural",
            "Present active imperative, 2nd person plural",
            "Aorist passive subjunctive, 2nd person plural",
            "Perfect active indicative, 2nd person plural",
        ],
        "correct": 0,
        "explanation": "MorphGNT: ἁγιάσατε = V- 2AAD-P--, aorist active imperative, 2nd plural, от ἁγιάζω. Это морфология; адресат повеления и его богословское значение анализируются отдельно.",
        "verse": "1 Пет. 3:15", "topic": "Greek: ἁγιάσατε", "claim_type": "greek", "confidence": "high", "position": "neutral", "competitive": False,
        "sources": ["sblgnt", "morphgnt_1peter"],
    },
    {
        "id": "ch3_gr_302",
        "question": "Что морфологически общего у κύριον и τὸν Χριστόν?",
        "options": [
            "Оба существительных стоят в accusative masculine singular",
            "Оба существительных стоят в nominative masculine singular",
            "κύριον — accusative singular, а Χριστόν — genitive singular",
            "κύριον — dative singular, а Χριστόν — accusative plural",
        ],
        "correct": 0,
        "explanation": "κύριον = N- ----ASM-, Χριστόν = N- ----ASM-, τὸν = RA ----ASM-. Морфология не решает спор о предикативном или аппозиционном анализе κύριον и сама по себе не является христологическим выводом.",
        "verse": "1 Пет. 3:15", "topic": "Greek: κύριον τὸν Χριστόν", "claim_type": "greek", "confidence": "high", "position": "neutral", "competitive": False,
        "sources": ["sblgnt", "morphgnt_1peter"],
    },
    {
        "id": "ch3_gr_303",
        "question": "Как MorphGNT разбирает сочетание ἕτοιμοι ἀεί?",
        "options": [
            "ἕτοιμοι — adjective nominative masculine plural; ἀεί — adverb",
            "ἕτοιμοι — adjective accusative masculine plural; ἀεί — adverb",
            "ἕτοιμοι — present active participle plural; ἀεί — conjunction",
            "ἕτοιμοι — adjective nominative singular; ἀεί — preposition",
        ],
        "correct": 0,
        "explanation": "ἕτοιμοι = A- ----NPM-, ἀεί = D- --------. Морфология фиксирует прилагательное во множественном числе и наречие; прагматический вывод о том, как именно применять готовность, относится к следующему слою.",
        "verse": "1 Пет. 3:15", "topic": "Greek: ἕτοιμοι ἀεί", "claim_type": "greek", "confidence": "high", "position": "neutral", "competitive": False,
        "sources": ["sblgnt", "morphgnt_1peter"],
    },
    {
        "id": "ch3_gr_304",
        "question": "Какова морфологическая форма ἀπολογίαν в πρὸς ἀπολογίαν?",
        "options": [
            "Noun accusative feminine singular",
            "Noun dative feminine singular",
            "Noun genitive feminine plural",
            "Adjective accusative feminine singular",
        ],
        "correct": 0,
        "explanation": "ἀπολογίαν = N- ----ASF-; πρός здесь употреблено с accusative. Лексически речь идёт о защите/ответе, но морфологическая форма не выбирает одну современную apologetics methodology.",
        "verse": "1 Пет. 3:15", "topic": "Greek: πρὸς ἀπολογίαν", "claim_type": "greek", "confidence": "high", "position": "neutral", "competitive": False,
        "sources": ["sblgnt", "morphgnt_1peter", "bdag_3"],
    },
    {
        "id": "ch3_gr_305",
        "question": "Как MorphGNT разбирает αἰτοῦντι в παντὶ τῷ αἰτοῦντι?",
        "options": [
            "Present active participle, dative masculine singular",
            "Present middle participle, dative masculine singular",
            "Aorist active participle, accusative masculine singular",
            "Present active indicative, third person singular",
        ],
        "correct": 0,
        "explanation": "αἰτοῦντι = V- -PAPDSM-. παντί и τῷ также dative masculine singular. Это грамматически описывает «каждого спрашивающего»; вывод о конкретной социальной сцене требует дополнительной экзегезы.",
        "verse": "1 Пет. 3:15", "topic": "Greek: παντὶ τῷ αἰτοῦντι", "claim_type": "greek", "confidence": "high", "position": "neutral", "competitive": False,
        "sources": ["sblgnt", "morphgnt_1peter"],
    },
    {
        "id": "ch3_gr_306",
        "question": "Какие формы у λόγον и ἐλπίδος в 1 Пет. 3:15?",
        "options": [
            "λόγον — acc. masc. sg.; ἐλπίδος — gen. fem. sg.",
            "λόγον — nom. masc. sg.; ἐλπίδος — dat. fem. sg.",
            "λόγον — gen. masc. sg.; ἐλπίδος — acc. fem. sg.",
            "λόγον — dat. masc. pl.; ἐλπίδος — gen. fem. pl.",
        ],
        "correct": 0,
        "explanation": "λόγον = N- ----ASM-, ἐλπίδος = N- ----GSF-. Синтаксически запрашиваемый λόγος относится к надежде; конкретная позднейшая методология этими падежами не кодируется.",
        "verse": "1 Пет. 3:15", "topic": "Greek: λόγον / ἐλπίδος", "claim_type": "greek", "confidence": "high", "position": "neutral", "competitive": False,
        "sources": ["sblgnt", "morphgnt_1peter"],
    },
    {
        "id": "ch3_gr_307",
        "question": "Каковы формы πραΰτητος и φόβου после μετά?",
        "options": [
            "Оба существительных стоят в genitive singular",
            "Оба существительных стоят в accusative singular",
            "πραΰτητος — genitive singular, а φόβου — dative singular",
            "πραΰτητος — nominative plural, а φόβου — genitive plural",
        ],
        "correct": 0,
        "explanation": "πραΰτητος = N- ----GSF-, φόβου = N- ----GSM-. После μετά с genitive они входят в описание манеры ответа; точный прагматический оттенок φόβος определяется контекстом, не падежом.",
        "verse": "1 Пет. 3:15-16", "topic": "Greek: πραΰτης / φόβος", "claim_type": "greek", "confidence": "high", "position": "neutral", "competitive": False,
        "sources": ["sblgnt", "morphgnt_1peter", "bdag_3"],
    },
    {
        "id": "ch3_gr_308",
        "question": "Как MorphGNT разбирает συνείδησιν ἔχοντες ἀγαθήν?",
        "options": [
            "συνείδησιν/ἀγαθήν — acc. fem. sg.; ἔχοντες — pres. act. ptcp. nom. masc. pl.",
            "συνείδησιν/ἀγαθήν — gen. fem. sg.; ἔχοντες — pres. act. ptcp. acc. masc. pl.",
            "συνείδησιν — acc. fem. sg.; ἀγαθήν — nom. fem. sg.; ἔχοντες — finite indicative",
            "συνείδησιν — dat. fem. sg.; ἀγαθήν — acc. fem. pl.; ἔχοντες — aorist passive ptcp.",
        ],
        "correct": 0,
        "explanation": "συνείδησιν = N- ----ASF-, ἔχοντες = V- -PAPNPM-, ἀγαθήν = A- ----ASF-. Формы подтверждают конструкцию «имея добрую совесть»; её роль в аргументе — интерпретационный вопрос.",
        "verse": "1 Пет. 3:16", "topic": "Greek: добрая совесть", "claim_type": "greek", "confidence": "high", "position": "neutral", "competitive": False,
        "sources": ["sblgnt", "morphgnt_1peter"],
    },
    {
        "id": "ch3_gr_309",
        "question": "Как MorphGNT разбирает θέλοι в 1 Пет. 3:17?",
        "options": [
            "Present active optative, third person singular",
            "Present active indicative, third person singular",
            "Aorist active subjunctive, third person singular",
            "Present middle imperative, second person singular",
        ],
        "correct": 0,
        "explanation": "θέλοι = V- 3PAO-S--. С εἰ это поддерживает условный характер оборота о Божьей воле; сама морфология не решает всю проблему причинности и моральной ответственности за страдание.",
        "verse": "1 Пет. 3:17", "topic": "Greek: εἰ θέλοι", "claim_type": "greek", "confidence": "high", "position": "neutral", "competitive": False,
        "sources": ["sblgnt", "morphgnt_1peter"],
    },
]

__all__ = ["GREEK_3_13_17"]
