"""Reviewed sources for the 1 Peter 3:18-22 research lane.

Every entry records what was actually inspected.  Card eligibility is fail-closed:
metadata/bibliographic-only records are catalog controls, not substantive evidence.
"""

SOURCE_CATALOG = {
    "sblgnt": {
        "title": "SBL Greek New Testament",
        "url": "https://www.sblgnt.com/",
        "kind": "primary_text",
        "inspection_scope": "primary_text_inspected",
        "claim_limit": "The Greek wording of 1 Peter 3:18-22 used by this lane was inspected. This supports direct-text claims only; it does not support manuscript-distribution claims without a critical apparatus.",
    },
    "morphgnt_1peter": {
        "title": "MorphGNT / SBLGNT morphology: 1 Peter (81-1Pe-morphgnt.txt)",
        "url": "https://github.com/morphgnt/sblgnt/blob/master/81-1Pe-morphgnt.txt",
        "kind": "primary_text_morphology",
        "inspection_scope": "primary_text_inspected",
        "claim_limit": "The relevant 1 Peter 3:18-22 token/form/lemma/parse rows were inspected. MorphGNT supports morphology, not disputed semantic referents, chronology, or theology.",
    },
    "gty_1p3_18": {
        "title": "John MacArthur, The Triumph of Christ's Suffering, Part 1 (1 Peter 3:18)",
        "url": "https://www.gty.org/resources/study-guides/chapters/60-36/the-triumph-of-christs-suffering-part-1",
        "kind": "conservative_exposition_position",
        "inspection_scope": "relevant_section_inspected",
        "claim_limit": "Relevant 1 Peter 3:18 exposition was inspected. It supports MacArthur's passage-level once-for-all sin-bearing, righteous-for-unrighteous, access-to-God, suffering-to-triumph reading; it is an evangelical interpretive witness, not neutral lexical proof.",
        "project_passage_witness": True,
    },
    "gty_1p3_18_20": {
        "title": "John MacArthur, The Triumph of Christ's Suffering, Part 2 (1 Peter 3:18-20)",
        "url": "https://www.gty.org/sermons/60-37/the-triumph-of-christs-suffering-part-2",
        "kind": "conservative_exposition_position",
        "inspection_scope": "relevant_section_inspected",
        "claim_limit": "The relevant 1 Peter 3:18-20 sermon text was inspected. It supports MacArthur's flesh/spirit and fallen-spirit/victory-proclamation interpretation; it does not turn those conclusions into morphology or consensus.",
        "project_passage_witness": True,
    },
    "gty_1p3_20_22": {
        "title": "John MacArthur, The Triumph of Christ's Suffering, Part 3 (1 Peter 3:20-22)",
        "url": "https://www.gty.org/resources/study-guides/chapters/60-38/the-triumph-of-christs-suffering-part-3",
        "kind": "conservative_exposition_position",
        "inspection_scope": "relevant_section_inspected",
        "claim_limit": "The relevant 1 Peter 3:20-22 exposition was inspected. It supports MacArthur's non-automatic-water baptismal reading, appeal/pledge discussion, resurrection/exaltation, and suffering-to-triumph application; it is not lexical certainty or a neutral denominational formula.",
        "project_passage_witness": True,
    },
    "tgc_storms_1p3_18_22": {
        "title": "Sam Storms, 1 Peter Commentary: The Suffering and Vindication of Christ (3:18-22), The Gospel Coalition Bible Commentary",
        "url": "https://www.thegospelcoalition.org/commentary/1-peter/",
        "kind": "evangelical_passage_commentary",
        "inspection_scope": "relevant_section_inspected",
        "claim_limit": "The 1 Peter 3:18-22 section was inspected. It supports Storms's substitutionary 3:18 reading, risen-sphere/fallen-spirit interpretation, baptism-as-appeal-or-pledge / faith-union reading, and 3:22 vindication; it is an evangelical interpretive witness, not neutral morphology or lexical proof.",
        "project_passage_witness": True,
    },
    "grudem_noah_1p3_19": {
        "title": "Wayne Grudem, Christ Preaching through Noah: 1 Peter 3:19-20 in the Light of Dominant Themes in Jewish Literature, Trinity Journal 7.2 (Fall 1986), 3-31",
        "url": "https://www.waynegrudem.com/christ-preaching-through-noah-1-peter-319-20-in-the-light-of-dominant-themes-in-jewish-literature",
        "kind": "evangelical_scholarship_disputed",
        "inspection_scope": "relevant_section_inspected",
        "claim_limit": "Relevant sections of the author-hosted article PDF were inspected, including Grudem's statement and defense of Christ preaching through Noah and his comparison with competing readings. This is not an end-to-end full-article audit and does not make his reading a morphology fact.",
    },
    "jts_crawford_1p3_21": {
        "title": "Matthew R. Crawford, 'Confessing God from a Good Conscience': 1 Peter 3:21 and Early Christian Baptismal Theology, JTS 67.1 (2016), 23-37",
        "url": "https://academic.oup.com/jts/article/67/1/23/2451894",
        "kind": "peer_reviewed_scholarship_disputed",
        "inspection_scope": "publisher_abstract_inspected",
        "claim_limit": "The publisher abstract and metadata were inspected, not the full JTS article. The abstract supports that the phrase is disputed and reports Crawford's contractual/pledge argument and early-baptismal/confession line; it does not license lexical certainty or claims about uninspected article details.",
    },
    "ubs_handbook_1p3_21": {
        "title": "Daniel C. Arichea and Eugene A. Nida, A Handbook on The First Letter from Peter: translation commentary on 1 Peter 3:21 (UBS Handbook Series, 1980)",
        "url": "https://tips.translation.bible/tip_term/translation-commentary-on-1-peter-321/",
        "kind": "translation_handbook_lexical_control",
        "inspection_scope": "relevant_section_inspected",
        "claim_limit": "The publicly reproduced passage-level commentary on 1 Peter 3:21 was inspected. It supports the question/answer, appeal/request, contractual/pledge, and genitive-relationship translation possibilities it discusses; it does not settle denominational baptismal systematics.",
    },
    "pierce_spirits_2011": {
        "title": "Chad T. Pierce, Spirits and the Proclamation of Christ: 1 Peter 3:18-22 in Light of Sin and Punishment Traditions in Early Jewish and Christian Literature (WUNT II/305, 2011)",
        "url": "https://www.mohrsiebeck.com/en/book/spirits-and-the-proclamation-of-christ-9783161508585",
        "kind": "academic_monograph_disputed",
        "inspection_scope": "publisher_abstract_inspected",
        "claim_limit": "Only the publisher synopsis was inspected. It supports that Pierce studies 1 Peter 3:18-22 against Watchers/1 Enoch and related early Jewish sin-and-punishment traditions; it does not establish Pierce's detailed conclusions or any claim not stated in that synopsis.",
    },
    "grindheim_spirits_2024": {
        "title": "Sigurd Grindheim, Why does 1 Peter 3,19 Mention the Spirits in Custody?, Biblica 105.1 (2024), 113-126",
        "url": "https://poj.peeters-leuven.be/content.php?id=3293260&journal_code=BIB&url=article",
        "kind": "peer_reviewed_scholarship_disputed",
        "inspection_scope": "publisher_abstract_inspected",
        "claim_limit": "The journal abstract was inspected, not the full article. It supports only the abstract-level thesis that disobedient spirits associated with Noah's time are defeated and that this has a rhetorical function in 1 Peter; detailed argumentation is not claimed inspected.",
    },
    "marcar_noah_2017": {
        "title": "Katie Marcar, In the Days of Noah: Urzeit/Endzeit Correspondence and the Flood Tradition in 1 Peter 3-4, New Testament Studies 63.4 (2017), 550-566",
        "url": "https://www.cambridge.org/core/journals/new-testament-studies/article/abs/in-the-days-of-noah-urzeitendzeit-correspondence-and-the-flood-tradition-in-1-peter-34/58720AD2358313A6A579E3757FBE747B",
        "kind": "peer_reviewed_scholarship_disputed",
        "inspection_scope": "publisher_abstract_inspected",
        "claim_limit": "The Cambridge abstract was inspected, not the full article. It supports Marcar's stated broader Noah/flood Urzeit-Endzeit framing across 1 Peter 3-4 and the observation that scholarship often foregrounds Enochic material; it does not support uninspected detailed exegesis.",
    },
    "lei_descensus_2025": {
        "title": "Chi-Kin Lei, 1 Peter and Christ's Descent to the Dead in Its Early Christian Reception (WUNT II/636, 2025)",
        "url": "https://www.mohrsiebeck.com/en/book/1-peter-and-christs-descent-to-the-dead-in-its-early-christian-reception-9783161640414/",
        "kind": "academic_monograph_reception_disputed",
        "inspection_scope": "publisher_abstract_inspected",
        "claim_limit": "Only the publisher synopsis was inspected. It supports the historical importance of 1 Peter 3:19 for descensus reception and that Lei re-examines/challenges the modern detachment of the passage from that doctrine; it does not prove that the imprisoned spirits are human dead or expose uninspected monograph arguments.",
    },
    "davids_1peter_nicnt": {
        "title": "Peter H. Davids, The First Epistle of Peter (NICNT, 1990)",
        "url": "https://www.eerdmans.com/9781467422918/the-first-epistle-of-peter/",
        "kind": "evangelical_academic_commentary_bibliographic_control",
        "inspection_scope": "bibliographic_only",
        "claim_limit": "Bibliographic/product information only. The relevant 1 Peter 3:18-22 commentary section was not inspected, so this source is not card-eligible and cannot support an exact Davids position in this lane.",
    },
    "schreiner_1peter_nac": {
        "title": "Thomas R. Schreiner, 1, 2 Peter, Jude (New American Commentary)",
        "url": "https://www.bhpublishinggroup.com/product/1-2-peter-jude-2/",
        "kind": "evangelical_academic_commentary",
        "inspection_scope": "bibliographic_only",
        "claim_limit": "The available product/bibliographic page was inspected, not Schreiner's relevant 1 Peter 3:18-22 commentary section. This source is not card-eligible and cannot serve as project quorum in this lane.",
    },
    "elliott_1peter_ayb": {
        "title": "John H. Elliott, 1 Peter (Anchor Yale Bible, 2001)",
        "url": "https://yalebooks.yale.edu/book/9780300139914/1-peter/",
        "kind": "academic_commentary_bibliographic_control",
        "inspection_scope": "bibliographic_only",
        "claim_limit": "Bibliographic/product information only. Relevant 1 Peter 3:18-22 pages were not inspected, so the source is not card-eligible and no exact Elliott position is attributed.",
    },
    "horrell_williams_icc_v2": {
        "title": "David G. Horrell and Travis B. Williams, 1 Peter: A Critical and Exegetical Commentary, Vol. 2: Chapters 3-5 (ICC, 2023)",
        "url": "https://www.bloomsbury.com/us/1-peter-9780567710604/",
        "kind": "critical_academic_commentary",
        "inspection_scope": "metadata_only",
        "claim_limit": "Publisher metadata/description and table-of-contents level information were inspected, not the relevant ICC commentary pages. This source is not card-eligible and cannot support exact 3:18-22 claims in this lane.",
    },
    "westfall_baptism_1999": {
        "title": "Cynthia Long Westfall, The Relationship between the Resurrection, the Proclamation to the Spirits in Prison and Baptismal Regeneration: 1 Peter 3:19-22, in Resurrection (JSNTSup 186, 1999), 106-135",
        "url": "https://bible.ixtheo.de/Record/1535231688",
        "kind": "academic_chapter_baptism_disputed",
        "inspection_scope": "metadata_only",
        "claim_limit": "Bibliographic metadata/title/page range were verified (106-135), but the chapter argument was not inspected. This source is not card-eligible and cannot substantively support a baptismal reading in this lane.",
    },
    "lsj_eperotema": {
        "title": "LSJ, s.v. ἐπερώτημα, Scaife ATLAS",
        "url": "https://atlas.perseus.tufts.edu/dictionaries/entry/urn%3Acite2%3Ascaife-viewer%3Adictionaries.v1%3Alsj-n38734/",
        "kind": "historical_greek_lexicon",
        "inspection_scope": "relevant_section_inspected",
        "claim_limit": "The LSJ entry for ἐπερώτημα was inspected. It supports the lexical history/senses recorded there, including question/answer and legal-stipulation material; the lexicon alone does not settle the contextual translation of 1 Peter 3:21.",
    },
    "lxx_genesis_6": {
        "title": "Septuaginta (LXX), Genesis 6, Rahlfs-Hanhart / Deutsche Bibelgesellschaft",
        "url": "https://www.die-bibel.de/en/bible/LXX/GEN.6",
        "kind": "primary_text_lxx",
        "inspection_scope": "primary_text_inspected",
        "claim_limit": "Genesis 6 in the LXX was inspected as primary OT background. It can establish the Genesis wording/background used in this lane, not the identity of 1 Peter's spirits by morphology or direct literary dependence.",
    },
    "enoch_10_14_charles": {
        "title": "1 Enoch 10-14, R. H. Charles translation (primary Second Temple witness in translation)",
        "url": "https://www.ccel.org/c/charles/otpseudepig/enoch.htm",
        "kind": "primary_second_temple_translation",
        "inspection_scope": "primary_text_inspected",
        "claim_limit": "The bounded 1 Enoch 10-14 passages were inspected in R. H. Charles's public-domain translation. This is a primary witness in translation, not a critical textual edition; it can establish relevant Watchers confinement/judgment/message motifs but cannot prove direct literary dependence by 1 Peter.",
    },
}

__all__ = ["SOURCE_CATALOG"]
